
export const countries = [
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "FR", name: "France" },
  { code: "ML", name: "Mali" },
  { code: "SN", name: "Sénégal" },
  { code: "GH", name: "Ghana" },
  { code: "NG", name: "Nigeria" },
  { code: "BJ", name: "Bénin" },
  { code: "BF", name: "Burkina Faso" },
  { code: "CM", name: "Cameroun" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "République démocratique du Congo" },
  { code: "GA", name: "Gabon" },
  { code: "GN", name: "Guinée" },
  { code: "GW", name: "Guinée-Bissau" },
  { code: "GQ", name: "Guinée équatoriale" },
  { code: "MG", name: "Madagascar" },
  { code: "NE", name: "Niger" },
  { code: "CF", name: "République centrafricaine" },
  { code: "RW", name: "Rwanda" },
  { code: "ST", name: "Sao Tomé-et-Principe" },
  { code: "TG", name: "Togo" },
  { code: "TD", name: "Tchad" },
  { code: "DZ", name: "Algérie" },
  { code: "AO", name: "Angola" },
  { code: "ZA", name: "Afrique du Sud" },
  { code: "BW", name: "Botswana" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cap-Vert" },
  { code: "KM", name: "Comores" },
  { code: "DJ", name: "Djibouti" },
  { code: "EG", name: "Égypte" },
  { code: "ER", name: "Érythrée" },
  { code: "ET", name: "Éthiopie" },
  { code: "GM", name: "Gambie" },
  { code: "KE", name: "Kenya" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Libéria" },
  { code: "LY", name: "Libye" },
  { code: "MW", name: "Malawi" },
  { code: "MR", name: "Mauritanie" },
  { code: "MU", name: "Maurice" },
  { code: "MA", name: "Maroc" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibie" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SO", name: "Somalie" },
  { code: "SD", name: "Soudan" },
  { code: "SS", name: "Soudan du Sud" },
  { code: "SZ", name: "Eswatini" },
  { code: "TZ", name: "Tanzanie" },
  { code: "TN", name: "Tunisie" },
  { code: "UG", name: "Ouganda" },
  { code: "ZM", name: "Zambie" },
  { code: "ZW", name: "Zimbabwe" },
  // Autres pays du monde
  { code: "DE", name: "Allemagne" },
  { code: "US", name: "États-Unis" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "Royaume-Uni" },
  { code: "ES", name: "Espagne" },
  { code: "IT", name: "Italie" },
  { code: "PT", name: "Portugal" },
  { code: "BE", name: "Belgique" },
  { code: "CH", name: "Suisse" },
  { code: "LU", name: "Luxembourg" },
  { code: "NL", name: "Pays-Bas" },
  { code: "SE", name: "Suède" },
  { code: "NO", name: "Norvège" },
  { code: "DK", name: "Danemark" },
  { code: "FI", name: "Finlande" },
  { code: "IE", name: "Irlande" },
  { code: "AT", name: "Autriche" },
  { code: "GR", name: "Grèce" },
  { code: "PL", name: "Pologne" },
  { code: "CZ", name: "République tchèque" },
  { code: "SK", name: "Slovaquie" },
  { code: "HU", name: "Hongrie" },
  { code: "RO", name: "Roumanie" },
  { code: "BG", name: "Bulgarie" },
  { code: "HR", name: "Croatie" },
  { code: "SI", name: "Slovénie" },
  { code: "RS", name: "Serbie" },
  { code: "ME", name: "Monténégro" },
  { code: "AL", name: "Albanie" },
  { code: "MK", name: "Macédoine du Nord" },
  { code: "BA", name: "Bosnie-Herzégovine" },
  { code: "UA", name: "Ukraine" },
  { code: "BY", name: "Biélorussie" },
  { code: "RU", name: "Russie" },
  { code: "TR", name: "Turquie" },
  { code: "IL", name: "Israël" },
  { code: "SA", name: "Arabie saoudite" },
  { code: "AE", name: "Émirats arabes unis" },
  { code: "QA", name: "Qatar" },
  { code: "KW", name: "Koweït" },
  { code: "BH", name: "Bahreïn" },
  { code: "OM", name: "Oman" },
  { code: "JO", name: "Jordanie" },
  { code: "LB", name: "Liban" },
  { code: "SY", name: "Syrie" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "Iran" },
  { code: "AF", name: "Afghanistan" },
  { code: "PK", name: "Pakistan" },
  { code: "IN", name: "Inde" },
  { code: "BD", name: "Bangladesh" },
  { code: "NP", name: "Népal" },
  { code: "LK", name: "Sri Lanka" },
  { code: "MM", name: "Myanmar" },
  { code: "TH", name: "Thaïlande" },
  { code: "LA", name: "Laos" },
  { code: "KH", name: "Cambodge" },
  { code: "VN", name: "Viêt Nam" },
  { code: "MY", name: "Malaisie" },
  { code: "SG", name: "Singapour" },
  { code: "ID", name: "Indonésie" },
  { code: "PH", name: "Philippines" },
  { code: "TW", name: "Taïwan" },
  { code: "KR", name: "Corée du Sud" },
  { code: "JP", name: "Japon" },
  { code: "CN", name: "Chine" },
  { code: "MN", name: "Mongolie" },
  { code: "AU", name: "Australie" },
  { code: "NZ", name: "Nouvelle-Zélande" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée" },
  { code: "FJ", name: "Fidji" },
  { code: "SB", name: "Îles Salomon" },
  { code: "VU", name: "Vanuatu" },
  { code: "BR", name: "Brésil" },
  { code: "AR", name: "Argentine" },
  { code: "CL", name: "Chili" },
  { code: "UY", name: "Uruguay" },
  { code: "PY", name: "Paraguay" },
  { code: "BO", name: "Bolivie" },
  { code: "PE", name: "Pérou" },
  { code: "EC", name: "Équateur" },
  { code: "CO", name: "Colombie" },
  { code: "VE", name: "Venezuela" },
  { code: "GY", name: "Guyana" },
  { code: "SR", name: "Suriname" },
  { code: "GF", name: "Guyane française" },
  { code: "MX", name: "Mexique" },
  { code: "GT", name: "Guatemala" },
  { code: "BZ", name: "Belize" },
  { code: "SV", name: "Salvador" },
  { code: "HN", name: "Honduras" },
  { code: "NI", name: "Nicaragua" },
  { code: "CR", name: "Costa Rica" },
  { code: "PA", name: "Panama" },
  { code: "CU", name: "Cuba" },
  { code: "JM", name: "Jamaïque" },
  { code: "HT", name: "Haïti" },
  { code: "DO", name: "République dominicaine" },
  { code: "PR", name: "Porto Rico" },
];
